"use strict";

import {
  MSG_INIT_MAPS,
  MSG_INIT_PANO,
  MSG_INIT_KERNEL,
  MSG_KERNEL_READY,
  MSG_RENDER_CLASSIC,
  MSG_RENDER_PANORAMA,
  MSG_RENDER_PANO_VIEW,
  MSG_RENDER_CUBE_VIEW,
  MSG_RENDER_CUBE_GENERATE,
  MSG_RESULT_CLASSIC,
  MSG_RESULT_PANORAMA,
  MSG_RESULT_PANO_VIEW,
  MSG_RESULT_CUBE_VIEW,
  MSG_RESULT_CUBE_GENERATE,
  MSG_WORKER_ERROR,
  MSG_INIT_CUBE,
} from "../constants/threading.js";

export {
  MSG_INIT_MAPS,
  MSG_INIT_PANO,
  MSG_INIT_KERNEL,
  MSG_KERNEL_READY,
  MSG_RENDER_CLASSIC,
  MSG_RENDER_PANORAMA,
  MSG_RENDER_PANO_VIEW,
  MSG_RENDER_CUBE_VIEW,
  MSG_RENDER_CUBE_GENERATE,
  MSG_RESULT_CLASSIC,
  MSG_RESULT_PANORAMA,
  MSG_RESULT_PANO_VIEW,
  MSG_RESULT_CUBE_VIEW,
  MSG_RESULT_CUBE_GENERATE,
  MSG_WORKER_ERROR,
  MSG_INIT_CUBE,
};

export function classicRenderPayload(jobId, range, params) {
  return {
    type: MSG_RENDER_CLASSIC,
    jobId: jobId,
    startColumn: range.start,
    endColumn: range.end,
    screenWidth: params.screenWidth,
    screenHeight: params.screenHeight,
    camX: params.camX,
    camY: params.camY,
    camZ: params.camZ,
    sinAngle: params.sinAngle,
    cosAngle: params.cosAngle,
    tanHalfFovX: params.tanHalfFovX,
    dstToProjPlane: params.dstToProjPlane,
    screenHorizon: params.screenHorizon,
    nearClip: params.nearClip,
    farClip: params.farClip,
    minDeltaZ: params.minDeltaZ,
    quality: params.quality,
    applyFog: params.applyFog,
    debugView: params.debugView,
    repeat: params.repeat,
    interpolateHeight: params.interpolateHeight,
    filterColor: params.filterColor,
    filterDistance: params.filterDistance,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    rowColors: params.rowColors,
  };
}

export function panoramaViewPayload(jobId, range, params) {
  return {
    type: MSG_RENDER_PANO_VIEW,
    jobId: jobId,
    startColumn: range.start,
    endColumn: range.end,
    screenWidth: params.screenWidth,
    screenHeight: params.screenHeight,
    fovY: params.fovY,
    dstToProjPlane: params.dstToProjPlane,
    skyColor: params.skyColor,
    horizonColor: params.horizonColor,
    nearClip: params.nearClip,
    farClip: params.farClip,
    applyFog: params.applyFog,
    debugView: params.debugView,
    rightX: params.rightX,
    rightY: params.rightY,
    rightZ: params.rightZ,
    upX: params.upX,
    upY: params.upY,
    upZ: params.upZ,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    fwdZ: params.fwdZ,
  };
}

export function cubemapViewPayload(jobId, range, params) {
  return {
    type: MSG_RENDER_CUBE_VIEW,
    jobId: jobId,
    startColumn: range.start,
    endColumn: range.end,
    screenWidth: params.screenWidth,
    screenHeight: params.screenHeight,
    cubeN: params.cubeN,
    fovY: params.fovY,
    dstToProjPlane: params.dstToProjPlane,
    skyColor: params.skyColor,
    horizonColor: params.horizonColor,
    nearClip: params.nearClip,
    farClip: params.farClip,
    applyFog: params.applyFog,
    debugView: params.debugView,
    rightX: params.rightX,
    rightY: params.rightY,
    rightZ: params.rightZ,
    upX: params.upX,
    upY: params.upY,
    upZ: params.upZ,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    fwdZ: params.fwdZ,
  };
}

export function cubemapGeneratePayload(jobId, job, params) {
  return {
    type: MSG_RENDER_CUBE_GENERATE,
    jobId: jobId,
    kind: job.kind,
    face: job.face,
    startAz: job.startAz | 0,
    endAz: job.endAz | 0,
    fillSky: job.fillSky | 0,
    n: params.n,
    camX: params.camX,
    camY: params.camY,
    camZ: params.camZ,
    farClip: params.farClip,
    nearClip: params.nearClip,
    tMax: params.tMax,
    repeat: params.repeat,
    skyColor: params.skyColor,
    horizonColor: params.horizonColor,
    initialStep: params.initialStep,
    quality: params.quality,
    interpolateHeight: params.interpolateHeight,
    filterColor: params.filterColor,
    filterDistance: params.filterDistance,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    wantHeight: params.wantHeight | 0,
    wantIter: params.wantIter | 0,
    shared: params.shared | 0,
    color: params.color || null,
    depth: params.depth || null,
    heightBuf: params.heightBuf || null,
    iterBuf: params.iterBuf || null,
  };
}

export function panoramaGeneratePayload(jobId, range, params) {
  return {
    type: MSG_RENDER_PANORAMA,
    jobId: jobId,
    startPx: range.start,
    endPx: range.end,
    width: params.width,
    height: params.height,
    camX: params.camX,
    camY: params.camY,
    camZ: params.camZ,
    farClip: params.farClip,
    nearClip: params.nearClip,
    tMax: params.tMax,
    repeat: params.repeat,
    skyColor: params.skyColor,
    horizonColor: params.horizonColor,
    initialStep: params.initialStep,
    quality: params.quality,
    interpolateHeight: params.interpolateHeight,
    filterColor: params.filterColor,
    filterDistance: params.filterDistance,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    wantHeight: params.wantHeight | 0,
    wantIter: params.wantIter | 0,
  };
}
