"use strict";

import {
  MSG_INIT_MAPS,
  MSG_INIT_KERNEL,
  MSG_KERNEL_READY,
  MSG_RENDER_CLASSIC,
  MSG_RENDER_FRUSTUM_SPACE,
  MSG_RENDER_VOXEL,
  MSG_RESULT_CLASSIC,
  MSG_RESULT_FRUSTUM_SPACE,
  MSG_RESULT_VOXEL,
  MSG_WORKER_ERROR,
} from "../constants/threading.js";

export {
  MSG_INIT_MAPS,
  MSG_INIT_KERNEL,
  MSG_KERNEL_READY,
  MSG_RENDER_CLASSIC,
  MSG_RENDER_FRUSTUM_SPACE,
  MSG_RENDER_VOXEL,
  MSG_RESULT_CLASSIC,
  MSG_RESULT_FRUSTUM_SPACE,
  MSG_RESULT_VOXEL,
  MSG_WORKER_ERROR,
};

export function classicRenderPayload(jobId, range, params) {
  return {
    type: MSG_RENDER_CLASSIC,
    jobId: jobId,
    startColumn: range.start,
    endColumn: range.end,
    screenWidth: params.screenWidth,
    screenHeight: params.screenHeight,
    camX: params.camX,
    camY: params.camY,
    camZ: params.camZ,
    sinAngle: params.sinAngle,
    cosAngle: params.cosAngle,
    tanHalfFovX: params.tanHalfFovX,
    dstToProjPlane: params.dstToProjPlane,
    screenHorizon: params.screenHorizon,
    nearClip: params.nearClip,
    farClip: params.farClip,
    quality: params.quality,
    fov: params.fov,
    showDetails: params.showDetails,
    applyFog: params.applyFog,
    fogStart: params.fogStart,
    debugView: params.debugView,
    repeat: params.repeat,
    lod0Refine: params.lod0Refine,
    lod0RefineCurve: params.lod0RefineCurve,
    filterDistance: params.filterDistance,
    mipCount: params.mipCount,
    lodSpacingMode: params.lodSpacingMode,
    lodSpacing: params.lodSpacing,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    rowColors: params.rowColors,
  };
}

export function frustumSpaceRenderPayload(jobId, range, params) {
  return {
    type: MSG_RENDER_FRUSTUM_SPACE,
    jobId: jobId,
    startColumn: range.start,
    endColumn: range.end,
    screenWidth: params.screenWidth,
    screenHeight: params.screenHeight,
    camX: params.camX,
    camY: params.camY,
    camZ: params.camZ,
    rightX: params.rightX,
    rightY: params.rightY,
    rightZ: params.rightZ,
    upX: params.upX,
    upY: params.upY,
    upZ: params.upZ,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    fwdZ: params.fwdZ,
    tanHalfFovX: params.tanHalfFovX,
    dstToProjPlane: params.dstToProjPlane,
    nearClip: params.nearClip,
    farClip: params.farClip,
    minDeltaZ: params.minDeltaZ,
    quality: params.quality,
    fov: params.fov,
    showDetails: params.showDetails,
    lod0Refine: params.lod0Refine,
    lod0RefineCurve: params.lod0RefineCurve,
    applyFog: params.applyFog,
    fogStart: params.fogStart,
    debugView: params.debugView,
    repeat: params.repeat,
    filterDistance: params.filterDistance,
    mipCount: params.mipCount,
    lodSpacingMode: params.lodSpacingMode,
    lodSpacing: params.lodSpacing,
    rowColors: params.rowColors,
  };
}

export function voxelRenderPayload(jobId, range, params) {
  return {
    type: MSG_RENDER_VOXEL,
    jobId: jobId,
    startColumn: range.start,
    endColumn: range.end,
    screenWidth: params.screenWidth,
    screenHeight: params.screenHeight,
    camX: params.camX,
    camY: params.camY,
    camZ: params.camZ,
    rightX: params.rightX,
    rightY: params.rightY,
    rightZ: params.rightZ,
    upX: params.upX,
    upY: params.upY,
    upZ: params.upZ,
    fwdX: params.fwdX,
    fwdY: params.fwdY,
    fwdZ: params.fwdZ,
    fovY: params.fovY,
    dstToProjPlane: params.dstToProjPlane,
    nearClip: params.nearClip,
    farClip: params.farClip,
    quality: params.quality,
    applyFog: params.applyFog,
    fogStart: params.fogStart,
    fogEnd: params.fogEnd,
    debugView: params.debugView,
    repeat: params.repeat,
    filterDistance: params.filterDistance,
    lod0Refine: params.lod0Refine,
    lod0RefineCurve: params.lod0RefineCurve,
    mipCount: params.mipCount,
    lodSpacingMode: params.lodSpacingMode,
    lodSpacing: params.lodSpacing,
    showDetails: params.showDetails,
    skyColor: params.skyColor,
    horizonColor: params.horizonColor,
  };
}

